#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-haven
Version  : 2.1.1
Release  : 30
URL      : https://cran.r-project.org/src/contrib/haven_2.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/haven_2.1.1.tar.gz
Summary  : Import and Export SPSS, Stata and SAS Files
Group    : Development/Tools
License  : MIT
Requires: R-haven-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-forcats
Requires: R-hms
Requires: R-readr
Requires: R-tibble
BuildRequires : R-Rcpp
BuildRequires : R-cli
BuildRequires : R-forcats
BuildRequires : R-hms
BuildRequires : R-pillar
BuildRequires : R-pkgconfig
BuildRequires : R-readr
BuildRequires : R-stringi
BuildRequires : R-tibble
BuildRequires : R-utf8
BuildRequires : buildreq-R
BuildRequires : pkgconfig(zlib)
BuildRequires : util-linux
BuildRequires : zlib-dev

%description
# haven <a href='https:/haven.tidyverse.org'><img src='man/figures/logo.png' align="right" height="139" /></a>

%package lib
Summary: lib components for the R-haven package.
Group: Libraries

%description lib
lib components for the R-haven package.


%prep
%setup -q -c -n haven

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571841690

%install
export SOURCE_DATE_EPOCH=1571841690
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library haven
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library haven
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library haven
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc haven || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/haven/DESCRIPTION
/usr/lib64/R/library/haven/INDEX
/usr/lib64/R/library/haven/LICENSE
/usr/lib64/R/library/haven/Meta/Rd.rds
/usr/lib64/R/library/haven/Meta/features.rds
/usr/lib64/R/library/haven/Meta/hsearch.rds
/usr/lib64/R/library/haven/Meta/links.rds
/usr/lib64/R/library/haven/Meta/nsInfo.rds
/usr/lib64/R/library/haven/Meta/package.rds
/usr/lib64/R/library/haven/Meta/vignette.rds
/usr/lib64/R/library/haven/NAMESPACE
/usr/lib64/R/library/haven/NEWS.md
/usr/lib64/R/library/haven/R/haven
/usr/lib64/R/library/haven/R/haven.rdb
/usr/lib64/R/library/haven/R/haven.rdx
/usr/lib64/R/library/haven/doc/datetimes.Rmd
/usr/lib64/R/library/haven/doc/datetimes.html
/usr/lib64/R/library/haven/doc/index.html
/usr/lib64/R/library/haven/doc/semantics.R
/usr/lib64/R/library/haven/doc/semantics.Rmd
/usr/lib64/R/library/haven/doc/semantics.html
/usr/lib64/R/library/haven/examples/iris.dta
/usr/lib64/R/library/haven/examples/iris.sas7bdat
/usr/lib64/R/library/haven/examples/iris.sav
/usr/lib64/R/library/haven/help/AnIndex
/usr/lib64/R/library/haven/help/aliases.rds
/usr/lib64/R/library/haven/help/figures/logo.png
/usr/lib64/R/library/haven/help/haven.rdb
/usr/lib64/R/library/haven/help/haven.rdx
/usr/lib64/R/library/haven/help/paths.rds
/usr/lib64/R/library/haven/html/00Index.html
/usr/lib64/R/library/haven/html/R.css
/usr/lib64/R/library/haven/tests/testthat.R
/usr/lib64/R/library/haven/tests/testthat/datetime-d.dta
/usr/lib64/R/library/haven/tests/testthat/datetime.sas7bdat
/usr/lib64/R/library/haven/tests/testthat/datetime.sav
/usr/lib64/R/library/haven/tests/testthat/formats.sas7bcat
/usr/lib64/R/library/haven/tests/testthat/hadley.sas7bdat
/usr/lib64/R/library/haven/tests/testthat/hadley.zip
/usr/lib64/R/library/haven/tests/testthat/helper-lump.R
/usr/lib64/R/library/haven/tests/testthat/helper-roundtrip.R
/usr/lib64/R/library/haven/tests/testthat/labelled-num-na.sav
/usr/lib64/R/library/haven/tests/testthat/labelled-num.sav
/usr/lib64/R/library/haven/tests/testthat/labelled-output.txt
/usr/lib64/R/library/haven/tests/testthat/labelled-spss-output.txt
/usr/lib64/R/library/haven/tests/testthat/labelled-str.sav
/usr/lib64/R/library/haven/tests/testthat/notes.dta
/usr/lib64/R/library/haven/tests/testthat/pillar_double.txt
/usr/lib64/R/library/haven/tests/testthat/pillar_integer.txt
/usr/lib64/R/library/haven/tests/testthat/pillar_spss_integer.txt
/usr/lib64/R/library/haven/tests/testthat/pillar_string.txt
/usr/lib64/R/library/haven/tests/testthat/pillar_tagged_na.txt
/usr/lib64/R/library/haven/tests/testthat/tagged-na-double.dta
/usr/lib64/R/library/haven/tests/testthat/tagged-na-int.dta
/usr/lib64/R/library/haven/tests/testthat/tagged-na.sas7bcat
/usr/lib64/R/library/haven/tests/testthat/tagged-na.sas7bdat
/usr/lib64/R/library/haven/tests/testthat/tagged-na.txt
/usr/lib64/R/library/haven/tests/testthat/test-as-factor.R
/usr/lib64/R/library/haven/tests/testthat/test-labelled.R
/usr/lib64/R/library/haven/tests/testthat/test-labelled_spss.R
/usr/lib64/R/library/haven/tests/testthat/test-pillar.R
/usr/lib64/R/library/haven/tests/testthat/test-read-connection.R
/usr/lib64/R/library/haven/tests/testthat/test-read-sas.R
/usr/lib64/R/library/haven/tests/testthat/test-read-sav.R
/usr/lib64/R/library/haven/tests/testthat/test-read-stata.R
/usr/lib64/R/library/haven/tests/testthat/test-read-xpt.R
/usr/lib64/R/library/haven/tests/testthat/test-replace_with.R
/usr/lib64/R/library/haven/tests/testthat/test-tagged_na.R
/usr/lib64/R/library/haven/tests/testthat/test-utils.R
/usr/lib64/R/library/haven/tests/testthat/test-write-dta.R
/usr/lib64/R/library/haven/tests/testthat/test-write-sas.R
/usr/lib64/R/library/haven/tests/testthat/test-write-sav.R
/usr/lib64/R/library/haven/tests/testthat/test-write-xpt.R
/usr/lib64/R/library/haven/tests/testthat/test-zap-empty.R
/usr/lib64/R/library/haven/tests/testthat/test-zap_label.R
/usr/lib64/R/library/haven/tests/testthat/test-zap_labels.R
/usr/lib64/R/library/haven/tests/testthat/test-zap_missing.R
/usr/lib64/R/library/haven/tests/testthat/test-zap_widths.R
/usr/lib64/R/library/haven/tests/testthat/types.dta
/usr/lib64/R/library/haven/tests/testthat/umlauts.sav
/usr/lib64/R/library/haven/tests/testthat/variable-label.sav

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/haven/libs/haven.so
/usr/lib64/R/library/haven/libs/haven.so.avx2
/usr/lib64/R/library/haven/libs/haven.so.avx512
